- name: Dépoloiement de la base de données PostgreSQL
  hosts: bdd
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - bdd

- name: Dépoloiement de l'application FastAPI
  hosts: app
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - app